In [1]:
import pandas as pd

In [2]:
df_admission = pd.read_csv('ADMISSIONS.csv')

In [3]:
df_diagnoses=pd.read_csv('DIAGNOSES_ICD.csv')

In [4]:
df_ICD_desc = pd.read_csv('D_ICD_DIAGNOSES.csv')

In [5]:
df_diagnoses_desc=pd.merge(df_diagnoses, df_ICD_desc, on='ICD9_CODE')

In [12]:
df_diagnoses_desc

,ROW_ID_x,SUBJECT_ID,HADM_ID,SEQ_NUM,ICD9_CODE,ROW_ID_y,SHORT_TITLE,LONG_TITLE
0,1297,109,172335,1.0,40301,4312,Mal hyp kid w cr kid V,"Hypertensive chronic kidney disease, malignant..."
1,1311,109,173633,1.0,40301,4312,Mal hyp kid w cr kid V,"Hypertensive chronic kidney disease, malignant..."
2,1019,109,131345,1.0,40301,4312,Mal hyp kid w cr kid V,"Hypertensive chronic kidney disease, malignant..."
3,1039,109,131376,1.0,40301,4312,Mal hyp kid w cr kid V,"Hypertensive chronic kidney disease, malignant..."
4,1059,109,135923,1.0,40301,4312,Mal hyp kid w cr kid V,"Hypertensive chronic kidney disease, malignant..."
...,...,...,...,...,...,...,...,...
634704,650539,99873,143544,12.0,2982,2611,Reactive confusion,Reactive confusion
634705,640080,97547,112445,32.0,E9399,13518,Adv eff psychotropic NOS,Unspecified psychotropic agent causing adverse...
634706,639100,97339,198692,3.0,E0070,9621,Tackle football,Activities involving american tackle football
634707,631728,95806,167169,15.0,6940,7520,Dermatitis herpetiformis,Dermatitis herpetiformis
634708,632673,96023,116385,5.0,20930,2361,Malig neuroendo ca NOS,Malignant poorly differentiated neuroendocrine...

In [6]:
full_df = pd.merge(df_diagnoses_desc, df_admission, on=['SUBJECT_ID','HADM_ID'])

In [14]:
full_df

,ROW_ID_x,SUBJECT_ID,HADM_ID,SEQ_NUM,ICD9_CODE,ROW_ID_y,SHORT_TITLE,LONG_TITLE,ROW_ID,ADMITTIME,...,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA
0,1297,109,172335,1.0,40301,4312,Mal hyp kid w cr kid V,"Hypertensive chronic kidney disease, malignant...",128,2141-09-18 10:32:00,...,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2141-09-18 07:06:00,2141-09-18 11:25:00,LEG PAIN,0,1
1,1298,109,172335,2.0,486,5528,"Pneumonia, organism NOS","Pneumonia, organism unspecified",128,2141-09-18 10:32:00,...,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2141-09-18 07:06:00,2141-09-18 11:25:00,LEG PAIN,0,1
2,1299,109,172335,3.0,58281,5892,Chr nephritis in oth dis,Chronic glomerulonephritis in diseases classif...,128,2141-09-18 10:32:00,...,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2141-09-18 07:06:00,2141-09-18 11:25:00,LEG PAIN,0,1
3,1300,109,172335,4.0,5855,5913,Chron kidney dis stage V,"Chronic kidney disease, Stage V",128,2141-09-18 10:32:00,...,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2141-09-18 07:06:00,2141-09-18 11:25:00,LEG PAIN,0,1
4,1301,109,172335,5.0,4254,4435,Prim cardiomyopathy NEC,Other primary cardiomyopathies,128,2141-09-18 10:32:00,...,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2141-09-18 07:06:00,2141-09-18 11:25:00,LEG PAIN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634704,348883,30377,104237,2.0,E8852,9835,Fall from skateboard,Fall from skateboard,36991,2161-07-09 23:56:00,...,Private,ENGL,NOT SPECIFIED,SINGLE,HISPANIC OR LATINO,2161-07-09 20:25:00,2161-07-10 00:57:00,SKULL FRACTURE,0,1
634705,367995,31972,139331,1.0,75160,7584,Biliary & liver anom NOS,"Unspecified anomaly of gallbladder, bile ducts...",38796,2163-12-23 04:08:00,...,Private,ENGL,CATHOLIC,MARRIED,WHITE,NaN,NaN,ORGAN DONOR ACCOUNT,1,1
634706,290675,25951,115991,1.0,1885,1999,Mal neo bladder neck,Malignant neoplasm of bladder neck,31738,2116-06-12 10:00:00,...,Private,ENGL,NOT SPECIFIED,MARRIED,WHITE,NaN,NaN,BLADDER CANCER/SDA,0,1
634707,408989,46732,167513,1.0,64263,6671,Eclampsia-antepartum,"Eclampsia, antepartum condition or complication",41906,2170-04-07 13:03:00,...,Private,ENGL,OTHER,MARRIED,ASIAN - ASIAN INDIAN,2170-04-07 07:12:00,2170-04-07 14:30:00,SEIZURE,0,1
634708,523154,71275,157952,1.0,99561,10504,Anphylct react peanuts,Anaphylactic reaction due to peanuts,49869,2144-10-22 21:17:00,...,Private,ENGL,NOT SPECIFIED,SINGLE,OTHER,2144-10-22 20:30:00,2144-10-22 22:20:00,ALLERGIC REACTION,0,1

In [7]:
Cols= ['HADM_ID','ICD9_CODE', 'SHORT_TITLE']

In [8]:
uti= full_df[Cols]

In [9]:
uti

        HADM_ID ICD9_CODE               SHORT_TITLE
0        172335     40301    Mal hyp kid w cr kid V
1        172335       486   Pneumonia, organism NOS
2        172335     58281  Chr nephritis in oth dis
3        172335      5855  Chron kidney dis stage V
4        172335      4254   Prim cardiomyopathy NEC
...         ...       ...                       ...
634704   104237     E8852      Fall from skateboard
634705   139331     75160  Biliary & liver anom NOS
634706   115991      1885      Mal neo bladder neck
634707   167513     64263      Eclampsia-antepartum
634708   157952     99561    Anphylct react peanuts

[634709 rows x 3 columns]

In [10]:
unique_columns = ['HADM_ID', 'ICD9_CODE','SHORT_TITLE']
admissionwithdiagnoses = uti.drop_duplicates(subset=unique_columns)

In [11]:
admissionwithdiagnoses

        HADM_ID ICD9_CODE               SHORT_TITLE
0        172335     40301    Mal hyp kid w cr kid V
1        172335       486   Pneumonia, organism NOS
2        172335     58281  Chr nephritis in oth dis
3        172335      5855  Chron kidney dis stage V
4        172335      4254   Prim cardiomyopathy NEC
...         ...       ...                       ...
634704   104237     E8852      Fall from skateboard
634705   139331     75160  Biliary & liver anom NOS
634706   115991      1885      Mal neo bladder neck
634707   167513     64263      Eclampsia-antepartum
634708   157952     99561    Anphylct react peanuts

[634649 rows x 3 columns]

In [12]:
# List of ICD9_CODEs of interest
desired_icd9_codes = [77181, 99591, 99592, 67020, 67022, 67024]

In [13]:
# Find unique HADM_IDs where ICD9_CODE is in desired_icd9_codes
hadm_ids_of_interest = admissionwithdiagnoses[admissionwithdiagnoses['ICD9_CODE'].isin(desired_icd9_codes)]['HADM_ID'].unique()

In [16]:
# Filter the original dataframe to keep only those HADM_IDs
filtered_df = admissionwithdiagnoses[admissionwithdiagnoses['HADM_ID'].isin(hadm_ids_of_interest)]

In [17]:
filtered_df

Empty DataFrame
Columns: [HADM_ID, ICD9_CODE, SHORT_TITLE]
Index: []

In [49]:
# 2.Filter original dataframe to keep only those HADM_IDs
filtered_df = admissionwithdiagnoses[admissionwithdiagnoses['HADM_ID'].isin(hadm_ids_with_sepsis)]

In [50]:
filtered_df

        HADM_ID ICD9_CODE               SHORT_TITLE
895      108977     40301    Mal hyp kid w cr kid V
896      108977       486   Pneumonia, organism NOS
897      108977      2762                  Acidosis
898      108977      5856   End stage renal disease
899      108977     41401  Crnry athrscl natve vssl
...         ...       ...                       ...
627772   155563     V3401  Oth mult lb-in hosp w cs
627773   155563      7702    NB interstit emphysema
627774   155563     76522   24 comp weeks gestation
627775   155563     77084   Resp failure of newborn
627776   155563     04184           Other anaerobes

[96157 rows x 3 columns]

In [40]:
# Filter original dataframe to keep only those HADM_IDs
filtered_df = admissionwithdiagnoses[admissionwithdiagnoses['HADM_ID'].isin(hadm_ids_with_sepsis)]

In [41]:
filtered_df

        HADM_ID ICD9_CODE               SHORT_TITLE
895      108977     40301    Mal hyp kid w cr kid V
896      108977       486   Pneumonia, organism NOS
897      108977      2762                  Acidosis
898      108977      5856   End stage renal disease
899      108977     41401  Crnry athrscl natve vssl
...         ...       ...                       ...
627772   155563     V3401  Oth mult lb-in hosp w cs
627773   155563      7702    NB interstit emphysema
627774   155563     76522   24 comp weeks gestation
627775   155563     77084   Resp failure of newborn
627776   155563     04184           Other anaerobes

[96157 rows x 3 columns]

In [47]:
filtered_df.to_csv('PatientswithSepsis.csv', index=False)

In [42]:
hadmid = filtered_df['HADM_ID'].unique()[:10]

In [43]:
sampledf = filtered_df[filtered_df['HADM_ID'].isin(hadmid)]

In [44]:
sampledf

      HADM_ID ICD9_CODE               SHORT_TITLE
895    108977     40301    Mal hyp kid w cr kid V
896    108977       486   Pneumonia, organism NOS
897    108977      2762                  Acidosis
898    108977      5856   End stage renal disease
899    108977     41401  Crnry athrscl natve vssl
...       ...       ...                       ...
2286   128219      0389            Septicemia NOS
2287   128219     99592             Severe sepsis
2288   128219      2948  Mental disor NEC oth dis
2289   128219     78552              Septic shock
2290   128219      2967     Bipolor I current NOS

[161 rows x 3 columns]

In [46]:
sampledf.to_csv('Sampledata.csv', index=False)

In [52]:
# retrieve all sepsis icd code
sepsis_icd =  df_ICD_desc[df_ICD_desc.apply(lambda x:'sepsis' in x['SHORT_TITLE'].lower(),axis=1)]['ICD9_CODE'].values

In [53]:
sepsis_icd

array(['77181', '99591', '99592', '67020', '67022', '67024'], dtype=object)